# Validate the codebase using the linting and build scripts
name: Validate Codebase

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-codebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm run build --if-present
      - run: npm run lint:ci --if-present
