# From https://github.com/wagoid/commitlint-github-action?tab=readme-ov-file#about-extends-in-your-config-file
name: Validate commit messages

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      # Run the commitlint action, considering its own dependencies and yours as well 🚀
      # `github.workspace` is the path to your repository.
      - uses: wagoid/commitlint-github-action@v5
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules